### ISSUE TITLE
lambda behave does not work with recent mockito versions

### ISSUE THREAD

**Issue by christophsturm** [RichardWarburton/lambda-behave#88]
lambda behave works great with mockito 2.0.2-beta, but if i upgrade to 2.0.14-beta it fails because mockito uses bytebuddy instead of cglib now and no longer bundles cglib.

The root problem here is that the bundled cglib in mockito is not public and lamba-behave should not use it.

**Comment by RichardWarburton** [comment]
Hi Christoph,

Thanks for your bug report. I've pushed a fix in 612b178134723991f6c85343dde098f13f3d07c2 which adds an explicit dependency on cglib.

**Comment by christophsturm** [comment]
thanks! are you planning a new release soon?

**Comment by RichardWarburton** [comment]
I wasn't - but if the current situation is causing you trouble I can push a release out.

**Comment by christophsturm** [comment]
no, we are running from git anyway. but would like to move to a release at some point, and master has lost of unreleased fixes.

**Comment by RichardWarburton** [comment]
In that case I'll try to get a release out this week.

**Comment by christophsturm** [comment]
thanks!

**Comment by RichardWarburton** [comment]
Hi @christophsturm apologies for my delay in getting back to you on this front. I've just done a release of 0.4. It should propagate to maven central soon. Let me know if there's any issues.
