### ISSUE TITLE
Android support via robolectric

### ISSUE THREAD

**Issue by bangarharshit** [RichardWarburton/lambda-behave#95]
I tried maintaining a similar library on my [own](https://github.com/bangarharshit/Oleaster) which was a fork of another library [Oleaster](https://github.com/mscharhag/oleaster) + robolectric.  

This library looks more maintained and would love to use it on android. Are you open to PR for robolectric?

**Comment by RichardWarburton** [comment]
To be honest, I'm not actively maintaining this library. but you're more than welcome to grab any code that will help your project, since the licenses are compatible.
